#!/bin/bash

# Find the absolute path of the directory where this script is located
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

# Open gThumb and view all images in this directory and its subdirectories
find "${SCRIPT_DIR}" -type f -name "*.jpg" -o  -name "*.png" -exec gthumb {} + &
